combo_twist_filter:
  ros__parameters:
    filter_1:
      tau: 0.5
      damping: 0.8
      weights: '[]'
      num_samples: 5
      num_out_samples: 5
      out_weights: '[0.1, 0.2, 0.2, 0.25, 0.25]'
    filter_2:
      tau: 0.8
      damping: 0.8
      weights: '[]'
      num_samples: 10
      num_out_samples: 5
      out_weights: '[0.1, 0.2, 0.2, 0.25, 0.25]'
    linear_vel_max: 1.0
    linear_acc_max: 1.0
    angular_vel_max: 2.0
    angular_acc_max: 1.0
    timeout: 0.25